general.live_config_reload = true

[window]
opacity = 0.7

[font]

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"